CREATE DATABASE COLLAGE;
USE COLLAGE;

CREATE TABLE Student(
ROLL INT PRIMARY KEY,
NAME VARCHAR(20),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(50)
);
INSERT INTO Student VALUES(1,"RAJ",70,"C","PUNE"),(2,"RAJA",80,"B","DELHI"),(3,"RAJAT",90,"A","KOLKATA");
INSERT INTO Student VALUES(4,"som",78,"C","CHENNAI"),(5,"pulok",82,"B","DELHI"),(6,"adam",911,"O","SURAT");
INSERT INTO Student VALUES(7,"ppRAJ",9,"C","PUNE"),(8,"lRAJA",81,"B","PURI"),(9,"KRAJAT",99,"O","KOLKATA");

SELECT *FROM Student;
SELECT NAME,CITY FROM Student;
SELECT  *FROM Student WHERE MARKS>80;
SELECT  *FROM Student WHERE CITY="KOLKATA";
SELECT *FROM Student WHERE MARKS<90 AND CITY="DELHI";
SELECT *FROM Student WHERE MARKS+10>100;
SELECT *FROM Student WHERE MARKS between 80 AND 90;
SELECT *FROM Student WHERE CITY IN("KOLKATA","PUNE");
SELECT *FROM Student WHERE CITY NOT IN("KOLKATA","PUNE");
SELECT *FROM Student WHERE MARKS>75 LIMIT 3;
SELECT *FROM Student ORDER BY CITY DESC;
SELECT *FROM Student ORDER BY CITY ASC LIMIT 4;
SELECT MAX(MARKS) FROM Student;
SELECT MIN(MARKS) FROM Student;
SELECT COUNT(NAME) FROM Student;
SELECT AVG(MARKS) FROM Student;
SELECT CITY ,COUNT(NAME)
FROM Student 
GROUP BY CITY;

SELECT CITY,AVG(MARKS)
FROM Student
GROUP BY CITY
ORDER BY CITY DESC;



