CREATE DATABASE CLASS;
USE CLASS;
CREATE TABLE COMPANY(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY LONG
);

INSERT INTO COMPANY VALUES(1,"RAJA",56534),(2,"TUT",60000),(3,"LAXMAN",70000);
SELECT *FROM COMPANY;
